# Generated by Django 4.0.4 on 2023-04-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='build_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'webapp_build_designation',
            },
        ),
        migrations.CreateModel(
            name='Buildpass_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('designation_id', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('event_pass', models.BooleanField(default=True)),
                ('exp_date', models.DateField(null=True)),
                ('reg_created_at', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(max_length=200, null=True)),
                ('print_status', models.IntegerField(null=True)),
                ('print_count', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('other_designation', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('collected', models.IntegerField(null=True)),
                ('approved_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'webapp_buildpass_table',
            },
        ),
        migrations.CreateModel(
            name='eventpass_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'webapp_eventpass_designation',
            },
        ),
        migrations.CreateModel(
            name='eventpass_image_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'webapp_eventpass_image_db',
            },
        ),
        migrations.CreateModel(
            name='Eventpass_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('designation_id', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('exp_date', models.DateField(null=True)),
                ('reg_created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='media/event_pass/profile')),
                ('id_proof_img', models.FileField(null=True, upload_to='media/event_pass/idproof')),
                ('id_proof_back_img', models.FileField(null=True, upload_to='media/event_pass/idproof')),
                ('UID', models.CharField(max_length=200, null=True)),
                ('print_status', models.IntegerField(null=True)),
                ('print_count', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('id_proof_cat', models.IntegerField(null=True)),
                ('id_proof', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField(null=True)),
                ('other_designation', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('collected', models.IntegerField(null=True)),
                ('approved_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'webapp_eventpass_table',
            },
        ),
        migrations.CreateModel(
            name='Unique_reg_code',
            fields=[
                ('urcode', models.CharField(default='29E80', editable=False, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unique_reg_code',
            },
        ),
        migrations.CreateModel(
            name='user_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('role', models.IntegerField(null=True)),
                ('is_online', models.IntegerField(null=True)),
                ('last_req_updated_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'webapp_user_db',
            },
        ),
        migrations.CreateModel(
            name='vapp_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'webapp_vapp_category',
            },
        ),
        migrations.CreateModel(
            name='Vapp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('vehicle_number', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('category_id', models.IntegerField(null=True)),
                ('exp_date', models.DateField(null=True)),
                ('reg_created_at', models.DateTimeField(auto_now_add=True)),
                ('UID', models.CharField(max_length=200, null=True)),
                ('print_status', models.IntegerField(null=True)),
                ('print_count', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('approved_date', models.DateField(null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('mulkya', models.FileField(null=True, upload_to='media/vapp/mulkya')),
                ('emirates_id', models.FileField(null=True, upload_to='media/vapp/emirates_id')),
                ('emirates_id_back', models.FileField(null=True, upload_to='media/vapp/emirates_id')),
                ('vehicle_type_id', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('collected', models.IntegerField(null=True)),
                ('approved_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'webapp_vapp_table',
            },
        ),
        migrations.CreateModel(
            name='vapp_vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'vapp_vehicle_type',
            },
        ),
    ]
