# Generated by Django 4.0.4 on 2023-04-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unique_reg_code',
        ),
    ]
