# Generated by Django 4.0.4 on 2023-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_unique_reg_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unique_reg_code',
            name='id',
        ),
        migrations.AlterField(
            model_name='unique_reg_code',
            name='ur_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='URG'),
        ),
    ]
