# Generated by Django 4.0.4 on 2023-04-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_remove_unique_reg_code_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unique_reg_code',
            old_name='ur_code',
            new_name='id',
        ),
    ]
