# Generated by Django 4.0.4 on 2023-04-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_rename_ur_code_unique_reg_code_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unique_reg_code',
        ),
    ]
