# Generated by Django 4.0.4 on 2023-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_delete_unique_reg_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_reg_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='URG')),
            ],
            options={
                'db_table': 'app_unique_reg_code',
            },
        ),
    ]
