# Generated by Django 4.0.4 on 2023-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_unique_reg_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_reg_code',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='URG'),
        ),
    ]
