# Generated by Django 4.0.4 on 2023-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0011_delete_unique_reg_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_reg_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur_code', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_unique_reg_code',
            },
        ),
    ]
