# Generated by Django 4.0.4 on 2023-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0012_unique_reg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique_reg_code',
            name='used',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
