# Generated by Django 4.0.4 on 2023-04-27 12:23

import Portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0013_unique_reg_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique_reg_code',
            name='code',
            field=models.CharField(default=Portal.models.generate_code, max_length=6, unique=True),
        ),
    ]
