# Generated by Django 4.0.4 on 2023-04-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0014_unique_reg_code_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unique_reg_code',
            name='ur_code',
        ),
    ]
