# Generated by Django 4.0.4 on 2023-04-05 10:28

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200, null=True)),
                ('last_name', models.TextField(max_length=200, null=True)),
                ('designation', models.TextField(max_length=200, null=True)),
                ('company', models.TextField(max_length=200, null=True)),
                ('email', models.TextField(max_length=200, null=True)),
                ('mobile', models.TextField(max_length=200, null=True)),
                ('country', models.TextField(max_length=200, null=True)),
                ('traveling_from', models.TextField(max_length=200, null=True)),
                ('retun_date_time', models.DateTimeField(null=True)),
                ('outline_talk', models.DateTimeField(null=True)),
                ('passport_copy', models.FileField(upload_to=App.models.speaker_directory_path)),
                ('photo_upload', models.FileField(upload_to=App.models.speaker_directory_path)),
            ],
        ),
    ]
