# Generated by Django 4.0.4 on 2023-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerregistrations',
            name='depature_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='speakerregistrations',
            name='outline_talk',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='speakerregistrations',
            table='app_speakerregistrations',
        ),
    ]
