# Generated by Django 4.0.4 on 2023-04-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_speakerregistrations_depature_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='speakerregistrations',
            table='app_speakerRegistrations',
        ),
    ]
