# Generated by Django 4.0.4 on 2023-04-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_speakerregistrations_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='speakerregistrations',
            table='app_speakerregistrations',
        ),
    ]
