# Generated by Django 4.0.4 on 2023-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_speakerregistrations_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerregistrations',
            name='ksa_visa',
            field=models.IntegerField(null=True),
        ),
    ]
