# Generated by Django 4.0.4 on 2023-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_speakerregistrations_ksa_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerregistrations',
            name='approved_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speakerregistrations',
            name='collected',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speakerregistrations',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='speakerregistrations',
            name='print_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speakerregistrations',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speakerregistrations',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
