# Generated by Django 4.0.4 on 2023-04-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_speakerregistrations_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerregistrations',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
