# Generated by Django 3.2.16 on 2023-04-18 07:13

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_speakerregistrations_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200, null=True)),
                ('last_name', models.TextField(max_length=200, null=True)),
                ('designation', models.TextField(max_length=200, null=True)),
                ('company', models.TextField(max_length=200, null=True)),
                ('email', models.TextField(max_length=200, null=True)),
                ('mobile', models.TextField(max_length=200, null=True)),
                ('country', models.TextField(max_length=200, null=True)),
                ('passport_copy', models.FileField(upload_to=App.models.invited_directory_path)),
                ('photo_upload', models.FileField(upload_to=App.models.invited_directory_path)),
                ('ksa_visa', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('approved_by', models.IntegerField(null=True)),
                ('collected', models.IntegerField(null=True)),
                ('print_status', models.IntegerField(null=True)),
                ('remark', models.TextField(default='', null=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_invitedregistrations',
            },
        ),
    ]
