# Generated by Django 3.2.16 on 2023-04-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_reaso_to_attend_applicantregistrations_reason_to_attend'),
    ]

    operations = [
        migrations.CreateModel(
            name='occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.TextField(max_length=200, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'app_occupations',
            },
        ),
    ]
