# Generated by Django 4.0.4 on 2023-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_occupations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_reg_code',
            fields=[
                ('urcode', models.CharField(default='A8FEB', editable=False, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unique_reg_code',
            },
        ),
    ]
