# Generated by Django 4.0.4 on 2023-04-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_unique_reg_code_urcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_reg_code',
            name='urcode',
            field=models.CharField(default='AD63E', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
