# Generated by Django 4.0.4 on 2023-04-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_delete_unique_reg_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_reg_code',
            fields=[
                ('urcode', models.CharField(default='BF9A4', editable=False, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_unique_reg_code',
            },
        ),
    ]
