# Generated by Django 4.0.4 on 2023-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_unique_reg_code_urcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_reg_code',
            name='urcode',
            field=models.UUIDField(default='324383', editable=False, primary_key=True, serialize=False),
        ),
    ]
