# Generated by Django 4.0.4 on 2023-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_unique_reg_code_urcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_reg_code',
            name='urcode',
            field=models.CharField(default='14F34', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
