# Generated by Django 4.0.4 on 2023-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_unique_reg_code_urcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unique_reg_code',
            name='urcode',
        ),
        migrations.AddField(
            model_name='unique_reg_code',
            name='id',
            field=models.UUIDField(default='113483', editable=False, primary_key=True, serialize=False),
        ),
    ]
