# Generated by Django 4.0.4 on 2023-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_unique_reg_code_urcode_unique_reg_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unique_reg_code',
            name='id',
        ),
        migrations.AddField(
            model_name='unique_reg_code',
            name='u_id',
            field=models.UUIDField(default='468576', editable=False, primary_key=True, serialize=False),
        ),
    ]
