# Generated by Django 4.0.4 on 2023-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_remove_unique_reg_code_id_unique_reg_code_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_reg_code',
            name='u_id',
            field=models.UUIDField(default='820062', editable=False, primary_key=True, serialize=False),
        ),
    ]
