# Generated by Django 4.0.4 on 2023-04-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_unique_reg_code_u_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unique_reg_code',
        ),
    ]
