# Generated by Django 4.0.4 on 2023-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_delete_unique_reg_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_reg_code',
            fields=[
                ('id', models.UUIDField(default='300899', editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_unique_reg_code',
            },
        ),
    ]
