# Generated by Django 4.0.4 on 2023-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_unique_reg_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_reg_code',
            name='id',
            field=models.CharField(default='304023360167735579365273182257136328113', editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
