# Generated by Django 4.0.4 on 2023-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_delete_unique_reg_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantregistrations',
            name='reason_to_attend',
        ),
        migrations.AddField(
            model_name='applicantregistrations',
            name='occupation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invitedregistrations',
            name='intrested_in',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invitedregistrations',
            name='occupation',
            field=models.IntegerField(null=True),
        ),
    ]
