# Generated by Django 4.0.4 on 2023-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_remove_applicantregistrations_reason_to_attend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantregistrations',
            old_name='pre_attand',
            new_name='pre_attend',
        ),
        migrations.AddField(
            model_name='applicantregistrations',
            name='intrested_in',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invitedregistrations',
            name='pre_attend',
            field=models.IntegerField(null=True),
        ),
    ]
