# Generated by Django 4.0.4 on 2023-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_rename_pre_attand_applicantregistrations_pre_attend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedregistrations',
            name='urc_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
