# Generated by Django 4.0.4 on 2023-05-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_applicantregistrations_print_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantregistrations',
            name='print_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invitedregistrations',
            name='print_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='speakerregistrations',
            name='print_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
